# Autogenerated wrapper script for aws_c_cal_jll for aarch64-apple-darwin
export libaws_c_cal

JLLWrappers.@generate_wrapper_header("aws_c_cal")
JLLWrappers.@declare_file_product(libaws_c_cal)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_file_product(
        libaws_c_cal,
        "lib/libaws-c-cal.a",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
